package dev.itemguard.risk.model;

public enum SignalType {
    UNEXPLAINED_ITEM_GAIN,
    HIGH_VALUE_ITEM_BURST,
    RARE_ITEM_BURST,
    REPEATED_IDENTICAL_ITEMS,
    RAPID_ITEM_GAIN,
    SHULKER_HIGH_FLOW,
    SHULKER_RAPID_TRANSFER,
    ILLEGAL_ENCHANTMENT,
    OVER_LEVEL_ENCHANTMENT,
    CONFLICTING_ENCHANTMENTS,
    OVERSIZED_STACK,
    SUSPICIOUS_ATTRIBUTE,
    SUSPICIOUS_COMPONENT,
    COMPONENT_MODIFIED,
    CUSTOM_ITEM_METADATA,
    ABNORMAL_DURABILITY,
    SUSPICIOUS_CONTAINER_CONTENTS,
    CUSTOM_MAX_STACK,
    HUSKSYNC_DATA_APPLY,
    KNOWN_CONTAINER_SOURCE,
    HUSKSYNC_REPEATED_SYNC,
    HUSKSYNC_ROLLBACK_LIKE,
    HUSKSYNC_RAPID_RESTORE,
    DUPLICATE_FINGERPRINT
}
